### ISSUE TITLE
Hang frequently when connecting or fetching from server

### ISSUE THREAD

**Issue by soulawaker** [yuya373/emacs-slack#285] opened 2018-02-11 10:53 UTC
My Emacs version is `25.x`. I use `emacs-slack` with Spacemacs slack layer. When connecting with `slack-start`, it reconnect at least two, sometimes more times. Then when I try `slack-channel-select` and select a specific channel, it often reconnect and frequently hang entire Emacs some seconds or more minutes. Now it hang several ten minutes with `No Message in <specific channel>, fetching from server...`. 
In my environment, `slack-request-timeout` default value causes to connection fail, never success. So I increased that value to 50. It is not bad. And I try another value, 100, experimentally. It was only that I adjusted.

**Comment by halcyon** [comment] 2018-07-26 01:34
I experienced this problem too, but only when running emacs in the terminal. I determined the problem I was experiencing was being caused by an attempt to render images when no graphical system was present. @soulawaker Were you running emacs in the terminal?

**Comment by iamriel** [comment] 2018-10-01 16:31
I am also experiencing this, it's just saying `No Message in channel, fetching from server...` :(

@soulawaker did you find a fix for this one? Also, where do you set `slack-request-timeout`? Thanks!

**Comment by soulawaker** [comment] 2018-10-02 22:57
@iamriel No, after several trials I didn't use slack in emacs. BTW, maybe you can set variables for raw emacs in init.el or for spacemacs like me in dotspacemacs/user-config.

**Comment by MAliNaqvi** [comment] 2019-02-02 20:58
Same thing here. But I experience it with one specific user only.

**Closed** 2019-12-28 03:46 UTC
