### ISSUE TITLE
Symbol's value as variable is void: slack-room-history-request

### ISSUE THREAD

**Issue by NSGregory** [yuya373/emacs-slack#164] opened 2017-03-11 05:00 UTC
I attempted to install emacs-slack for the first time today from MELPA and I am getting this error:

Symbol's value as variable is void: slack-room-history-request

I've gone through the process of setting up the client id, secret, and token on slack.  I used slack-register-team.  But when I try slack-start I get this error.  I don't know what else would be useful to include here but I'm willing to provide more details if that would be helpful.

Thanks!

**Comment by fvdbeek** [comment] 2017-03-28 16:53
I get the same error upon installation emacs-slack version 20170325.929 from MELPA.

After installation I followed the instructions in the README to create a new app on [https://api.slack.com/apps](https://api.slack.com/apps). I also added permission scopes, as mentioned in issue #107. I called `slack-register-team`, which prompted for Team Name, Client ID, Client Secret and Token. It finished silently without errors. When I finally call `slack-start` I get the same error: `require: Symbol's value as variable is void: slack-room-history-request`

During the process, I notice two problems:
1. the procedure to get the token does not work as mentioned in the README. A call to `slack-register-team` does not prompt "Enter the code your browser displayed: ", nor redirects to an URL like [http://localhost:8080?code=181818181818.1819919191&state=](http://localhost:8080?code=181818181818.1819919191&state=). It only prompts for Token, after Team Name, Client ID and Client Secret. It seems there happens no authorization request at all.
2. the Permission Scopes in the "Add features and functionality" of "Building Apps for Slack" section don't include the "client" and "identify" scopes. The README states that emacs-slack needs the "client" scope for authorizatione.

Does this mean that authorization of a new emacs-slack installation is currently impossible?

**Comment by fvdbeek** [comment] 2017-03-28 20:39
The problem is solved by upgrading the emacs version.

The error appeared in emacs 24 (version 24.4+1-5 on debian stable). It probably is related to the missing macro `cl-defmethod` in emacs versions prior to 25.1: `Symbol's function definition is void: cl-defmethod`.

After compiling the bleeding-edge version from source (version 26.0.50 from [git://git.sv.gnu.org/emacs.git](git://git.sv.gnu.org/emacs.git)) it worked with a minor glitch. I had to increase the timeout with `(setq slack-request-timeout 15)` as mentioned in issue #161.

**Comment by yuya373** [comment] 2017-03-29 03:51
@fvdbeek 
> It only prompts for Token, after Team Name, Client ID and Client Secret. It seems there happens no authorization request at all.

this is bug. I think fixed in #171 

> the Permission Scopes in the "Add features and functionality" of "Building Apps for Slack" section don't include the "client" and "identify" scopes. 

Configuring permission scope at Slack web is not needed and recommended now.
I found this after 2241d2f170d93cb1b237944c80d6fb3c391d6990 then update d2591dc47b7968b313b8d7d2ac31dc8144a2c5ea.
I requested "client" scope at [runtime](https://github.com/yuya373/emacs-slack/blob/master/slack.el#L186)
setting permission scope from Slack web cause some api not working.

**Comment by wxjeacen** [comment] 2017-04-25 14:35
So, what is the status of this issue? I have confronted the same problem...

**Comment by fvdbeek** [comment] 2017-04-25 19:43
What version of emacs do you use? As mentioned above, my problem was solved by upgrading to a version above 25.1.

**Comment by ssefick** [comment] 2017-05-31 16:09
I am using 24.5.1, and I am getting the same message. I would appreciate any help getting this to work.

**Comment by ssefick** [comment] 2017-05-31 20:33
Is it necessary to run >24.4? If so, this should be included in the dependencies.

**Comment by yuya373** [comment] 2017-06-01 02:05
@ssefick please install cl-generic and then reload this package.
If it works, i will add cl-generic to dependencies. 
https://elpa.gnu.org/packages/cl-generic.html

**Comment by ssefick** [comment] 2017-06-01 11:12
@yuya373 I installed cl-generic, and I am still receiving the same message. Any other ideas would be of great help. I would love to use this wonderful package, but emacs 25+ requires a much more complicated build on rhel 7.3. Thank you for all of the help.

**Comment by yuya373** [comment] 2017-06-01 11:25
@ssefick restart emacs before `slack-start`?

**Comment by ssefick** [comment] 2017-06-01 12:42
Yes, I restarted emacs. If it is helpful, I have included the relevant part of my .emacs.

(el-get-bundle slack)
(use-package slack

  :commands (slack-start)
  :init
  (setq slack-buffer-emojify t) ;; if you want to enable emoji, default nil
  (setq slack-prefer-current-team t)
  :config
  (slack-register-team
   :name "removed"
   :default t
   :client-id "removed"
   :client-secret "removed"
   :token "removed"
   :subscribed-channels '(removed)))

 (use-package alert
  :commands (alert)
  :init
  (setq alert-default-style 'notifier))
;;--------------------------------------------------------------;;

;;--------------------------------------------------------------;;
(require 'cl-generic)
;;--------------------------------------------------------------;;

**Comment by ssefick** [comment] 2017-06-26 01:17
Thank you for this response. I am still having a problem getting emacs-slack to work. I have edited my .emacs file to include the above with my slack channel specific information where "...." below.

(slack-register team
  :default t 
....
)

I am unable to interact with slacks. I would appreciate any help, and I will provide any information that is needed. Thank you for all of the help.

**Closed** 2019-12-28 03:51 UTC
