### ISSUE TITLE
Failed to request slack-conversations-view: not_allowed_token_type

### ISSUE THREAD

**Issue by matthew-piziak** [yuya373/emacs-slack#431] opened 2019-03-29 19:06 UTC
Somewhere between ca6f52d and be6cf18, this error started popping up upon attempting to join a room.
```
Failed to request slack-conversations-view: not_allowed_token_type
```

**Comment by yuya373** [comment] 2019-03-30 04:30
It seems `client` scope do not have permission to `conversations.view` and `client.counts` api.

We seem to need to use the tokens obtained in these ways.
- https://github.com/yuya373/emacs-slack#how-to-get-client-id
- https://github.com/yuya373/emacs-slack#1-from-request-payload

**Comment by jaor** [comment] 2019-04-02 01:38
after the last update from melpa (today), i'm also seeing

    Failed to request slack-conversations-view: not_allowed_token_type

and that prevents slack to work at all, at least in my case.  i might be doing something wrong, but i have tried with tokens obtained both the easy and the hard way, with the same results.

**Comment by jaor** [comment] 2019-04-02 14:30
Restarting emacs with a new token obtained by method 1 has fixed the issue for me. Apologies for the noise.

**Comment by alwyn** [comment] 2019-07-17 15:21
Any more detailed instructions on how to get the 'xoxs-' token?

I have logged out of my workspace, logged back in, all the while preserving the network logs in developer tools and search just doesn't find 'xoxs-' anywhere.

**Comment by alwyn** [comment] 2019-07-17 17:38
I am getting 
the same issue using method 3 of getting a token.  Suspect it is either a permission problem or a token that got modified under me.

Questions about method 3:
1) Do you need to manually specify permissions in the app profile of Slack?
2) The README refers to slack-oauth2-auth requesting client scope for keeping it from generating new tokens, but I have no clue if it is a command or a setting or ???.

**Comment by jimerickson** [comment] 2019-07-18 19:59
i too am seeing this error (Failed to request slack-conversations-view: not_allowed_token_type) after following the directions exactly for the "hard method". is there any fix or work around yet?

**Comment by jimerickson** [comment] 2019-07-19 12:37
ok so i got one workspace to work with method 1, it has a token that starts with "xoxs-" and works fine but the other workspace has a token that starts with "xoxc-" and doesn't work. why the different prefixes? whats going on?

**Comment by alwyn** [comment] 2019-07-19 14:25
Slack has different types of tokens.  Following the hard way, I get an xoxp- token.  I think they differ in how they can be used.

I tried method 1, but my dumps had multiple changing _x_id values so I never got a combination that consistently worked.

Switched to using Ripcord until emacs-slack can work without all the fudging.

**Comment by jimerickson** [comment] 2019-07-19 15:08
well i tried method 3 (the hard way) again and got, as you did, a token starting with "xoxp-" which allows me to get the workspace log and event log and the on going conversations show up in the minibuffer. but when i try to join the room it gives the "not allowed token type" again. so we are getting closer i guess. should i try contacting slack about the different token types and what they do? or would that not be productive?

**Comment by alwyn** [comment] 2019-07-19 15:18
They have some info here [Slack token types](https://api.slack.com/docs/token-types)

Your issue comes back to my question about permissions, whether they should be manually configured in the app management or whether they should work by default.

Also how to keep tokens from changing.  My setup worked briefly and then it just stopped.

What I don't understand is how it is possible for me to use other 3rd party applications where I just supply a username/password for the slack workspace and the rest just happens behind the scenes.

**Comment by jimerickson** [comment] 2019-07-19 21:35
so i contacted slack and explained things. as expected they weren't very
helpful. but anyway here is their reply:

Thanks for your understanding here.

Connecting to our Slack app uses different scopes and tokens than your
typical Slack API app's access tokens. Our app access tokens are primarily
for the web API endpoints.

Therefore, you must use a session token in order to connect to the client.
However, we don't readily reveal session tokens.

Sorry that I don't have better news. I admit that your use is an
interesting one, it's just not one that we can support at the moment.

in light of this reply from slack is there anything to be done? is there
anyway to get a user token ("xoxp-") working with emacs-slack? i guess
there is probably not much to do. anyway thanks for you time and
consideration in this matter.

**Comment by NuclearKev** [comment] 2019-07-22 20:17
I am also having this issue. However, I made sure that the app had all the required permissions. Still doesn't work for me!

**Comment by gbelote** [comment] 2019-07-29 20:35
I'm having this issue, but the workarounds aren't working from me. It seems that Method 1 doesn't yield a `xoxp-` token (instead, it yields a `xoxc-` token). It behaves like they've tightened token security in web as well as the private conversations.view API.

Is there another way to find the `xoxs-` token?

**Comment by sarg** [comment] 2019-07-30 07:51
I think the cause is simply that the method `conversations.view` is deprecated.
It is not listed in API docs: https://api.slack.com/docs/conversations-api

**Comment by sarg** [comment] 2019-07-30 08:53
`conversations.view` isn't listed in official API docs. Browser version uses it, but seems only to optimize request count when opening slack for first time. Seems that `emacs-slack` uses the method for message history requests. Maybe we need to use `conversations.history` for that?

**Comment by NuclearKev** [comment] 2019-07-30 14:58
@sarg I did as you said and it works again!

**Comment by jimerickson** [comment] 2019-07-30 15:42
@sarg in what file did you replace slack-conversations-view with slack-conversations-history? slack-convesations.el?

**Comment by sarg** [comment] 2019-07-30 15:59
^ `slack-message-buffer.el`. But I've noticed that with this fix in place, whenever I open any room, it's "unread marker" resets to the very beginning. This thing have to be addressed as well.

**Comment by stephanpdx** [comment] 2019-07-30 16:13
I had a similar issue with token using method #3, but also run into a connection issue for localhost. 

I created the app and got the client id and secret. I also set the URL to http://localhost:8080 as instructed. However, for step 3, I get a prompt to install the app and, when I press "Install", I get a "Problem loading page" error: "Firefox can’t establish a connection to the server at localhost:8080."

The url does show a token, but then I copy it and put it into the configuration, and then start emacs-slack, I get the following error: "failed to request slack-client-counts: not_allowed_token_type".

I also checked the app in my workspace, and, under OAuth & Permissions, it shows an OAuth Access Token; however, using that token gives me the same error message.

**Comment by jimerickson** [comment] 2019-07-30 17:24
@stephanpdx same problem here even with the changes to slack-message-buffer.el mentioned above.

**Comment by sarg** [comment] 2019-07-31 08:26
Yeah, `slack-client-counts` also uses undocumented API method. It raises an error for me too. Seems that slack has tightened their api security and we have to adapt to that. The best way for me is to get rid of undocumented API methods calls and use only public ones.

**Comment by alexiscott** [comment] 2019-08-02 18:20
Using the latest from Melpa and a legacy token, I was also getting `not_allowed_token_type`. 
The fix for me to  `slack-message-buffer.el ` changing `slack-conversations-view` to `slack-conversations-history` seemed to solve it.

**Comment by jimerickson** [comment] 2019-08-02 19:36
i modified slack-message-buffer.el and used legacy tokens and still got slack-client-count error. wow.

**Comment by sarg** [comment] 2019-08-03 11:15
You could `(advice-add 'slack-counts-update :override #'ignore)` at the moment.

**Comment by jimerickson** [comment] 2019-08-03 11:34
thank you @sarg it worked!

**Comment by noonker** [comment] 2019-08-06 16:33
@jimerickson I did the same as you and forgot that I needed to `byte-recompile-file`. It's working now Thanks @sarg!

**Comment by costrouc** [comment] 2019-08-22 12:55
Is there a working fix for this yet? Does this require a PR? Looks like at this moment this requires several steps to fix.

**Comment by stephanpdx** [comment] 2019-08-23 05:03
I tried to fix it using the description above, but did not succeed.  I am not an elisp expert though.

**Comment by costrouc** [comment] 2019-08-23 12:40
@stephanpdx I found that the fixes above only "sort of" fixed the issues. But I still encounter plenty of `not_allowed_token_type` notifications. Things I did:

1. edit `slack-message-buffer.el` and replace `slack-conversations-view` -> `slack-conversations-history`
2. add `(advice-add 'slack-counts-update :override #'ignore)`

**Comment by 4t0m** [comment] 2019-09-05 19:24
Thanks for the help.  Where specifically do you add the advice-add line?

**Comment by bhutch29** [comment] 2019-09-09 18:00
@4t0m It doesnt need to be anywhere specific, just put it in your configuration somewhere so it runs when starting Emacs.

Looks like this change, and the associated `not_allowed_token_type` errors, break almost every aspect of the package. I cannot list unreads, view all threads, or many other tasks. The fixes listed above were enough to get basic message reading capabilities working, but that is all.

Does anyone have ideas for a path forward to implement a fix? It sounds like the root cause is Slack restricting the use of unofficial API calls... are there official calls that are effective replacements? I am happy to help contribute to the fixes, but I don't really know where to start.

**Comment by m4ldonado** [comment] 2019-09-30 08:59
I managed to get an xoxs token by opening a plain text snippet from slack in the browser.  The URL looks like this:
https://.YOURWORKSPACE.slack.com/files/LETTERS/LETTERS/snippet_name

As far as I can tell - this gives full functionality

**Comment by ybgwon** [comment] 2019-11-25 09:09
thanks @m4ldonado it works !

**Comment by ayberkt** [comment] 2019-12-27 12:27
What worked for me was:

1. Changing `slack-conversations-view` to `slack-conversations-history` as mentioned;
2. Adding `(advice-add 'slack-counts-update :override #'ignore)` to my `.emacs`.

Actually, (2) might have sufficed, I haven't checked it yet. Perhaps someone should create PR with these changes as it seems like the instructions in the README are outdated as of now.

**Closed** 2019-12-28 03:27 UTC
