### ISSUE TITLE
consistent hangs apparently on flyspell-post-command-hook

### ISSUE THREAD

**Issue by tinder-jonathanwilner** [yuya373/emacs-slack#347] opened 2018-09-13 12:54 UTC
Hi,

Related to my open issue about hangs, when I do signal USR2 to emacs, the Backtrace almost always posts something about flyspell-post-command-hook. 

Here's an example, where I was typing in a notmuch compose buffer, but emacs-slack is also active. The version is from master, with the new helm-slack PR merged.

  flyspell-post-command-hook()
  recursive-edit()
  debug(error (quit))
  read-from-minibuffer("Select Channel: " nil (keymap keymap (4 . ido-magic-delete-char) (6 . ido-magic-forward-char) (2 . ido-magic-backward-char) (63 . ido-completion-help) (left . ido-prev-match) (right . ido-next-match) (0 . ido-restrict-to-matches) (27 keymap (32 . ido-take-first-match)) (67108896 . ido-restrict-to-matches) (26 . ido-undo-merge-work-directory) (20 . ido-toggle-regexp) (67108908 . ido-prev-match) (67108910 . ido-next-match) (19 . ido-next-match) (18 . ido-prev-match) (16 . ido-toggle-prefix) (13 . ido-exit-minibuffer) (10 . ido-select-text) (32 . ido-complete-space) (9 . ido-complete) (5 . ido-edit-input) (3 . ido-toggle-case) (1 . ido-toggle-ignore) keymap (18 . helm-minibuffer-history) (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the minibuffer") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuffer") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence "\015" :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (10 . exit-minibuffer) (13 . exit-minibuffer) (7 . minibuffer-keyboard-quit) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-line-or-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-line-or-history-element) (next . next-history-element) (27 keymap (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) nil nil)
  ido-read-internal(list "Select Channel: " nil nil t nil)
  #f(compiled-function (prompt choices &optional predicate require-match initial-input hist def inherit-input-method) "Ido replacement for the built-in `completing-read'.\nRead a string in the minibuffer with Ido-style completion.\nPROMPT is a string to prompt with; normally it ends in a colon and a space.\nCHOICES is a list of strings which are the possible completions.\nPREDICATE and INHERIT-INPUT-METHOD are currently ignored; they are included\n to be compatible with `completing-read'.\nIf REQUIRE-MATCH is non-nil, the user is not allowed to exit unless\n the input is (or completes to) an element of CHOICES or is null.\n If the input is null, `ido-completing-read' returns DEF, or an empty\n string if DEF is nil, regardless of the value of REQUIRE-MATCH.\nIf INITIAL-INPUT is non-nil, insert it in the minibuffer initially,\n with point positioned at the end.\nHIST, if non-nil, specifies a history list.\nDEF, if non-nil, is the default value." #<bytecode 0x466e3a49>)("Select Channel: " nil nil t nil)
  apply(#f(compiled-function (prompt choices &optional predicate require-match initial-input hist def inherit-input-method) "Ido replacement for the built-in `completing-read'.\nRead a string in the minibuffer with Ido-style completion.\nPROMPT is a string to prompt with; normally it ends in a colon and a space.\nCHOICES is a list of strings which are the possible completions.\nPREDICATE and INHERIT-INPUT-METHOD are currently ignored; they are included\n to be compatible with `completing-read'.\nIf REQUIRE-MATCH is non-nil, the user is not allowed to exit unless\n the input is (or completes to) an element of CHOICES or is null.\n If the input is null, `ido-completing-read' returns DEF, or an empty\n string if DEF is nil, regardless of the value of REQUIRE-MATCH.\nIf INITIAL-INPUT is non-nil, insert it in the minibuffer initially,\n with point positioned at the end.\nHIST, if non-nil, specifies a history list.\nDEF, if non-nil, is the default value." #<bytecode 0x466e3a49>) ("Select Channel: " nil nil t nil))
  ido-completing-read@ido-cr+-replace(#f(compiled-function (prompt choices &optional predicate require-match initial-input hist def inherit-input-method) "Ido replacement for the built-in `completing-read'.\nRead a string in the minibuffer with Ido-style completion.\nPROMPT is a string to prompt with; normally it ends in a colon and a space.\nCHOICES is a list of strings which are the possible completions.\nPREDICATE and INHERIT-INPUT-METHOD are currently ignored; they are included\n to be compatible with `completing-read'.\nIf REQUIRE-MATCH is non-nil, the user is not allowed to exit unless\n the input is (or completes to) an element of CHOICES or is null.\n If the input is null, `ido-completing-read' returns DEF, or an empty\n string if DEF is nil, regardless of the value of REQUIRE-MATCH.\nIf INITIAL-INPUT is non-nil, insert it in the minibuffer initially,\n with point positioned at the end.\nHIST, if non-nil, specifies a history list.\nDEF, if non-nil, is the default value." #<bytecode 0x466e3a49>) "Select Channel: " nil nil t nil)
  apply(ido-completing-read@ido-cr+-replace #f(compiled-function (prompt choices &optional predicate require-match initial-input hist def inherit-input-method) "Ido replacement for the built-in `completing-read'.\nRead a string in the minibuffer with Ido-style completion.\nPROMPT is a string to prompt with; normally it ends in a colon and a space.\nCHOICES is a list of strings which are the possible completions.\nPREDICATE and INHERIT-INPUT-METHOD are currently ignored; they are included\n to be compatible with `completing-read'.\nIf REQUIRE-MATCH is non-nil, the user is not allowed to exit unless\n the input is (or completes to) an element of CHOICES or is null.\n If the input is null, `ido-completing-read' returns DEF, or an empty\n string if DEF is nil, regardless of the value of REQUIRE-MATCH.\nIf INITIAL-INPUT is non-nil, insert it in the minibuffer initially,\n with point positioned at the end.\nHIST, if non-nil, specifies a history list.\nDEF, if non-nil, is the default value." #<bytecode 0x466e3a49>) ("Select Channel: " nil nil t nil))
  ido-completing-read("Select Channel: " nil nil t nil)
  funcall(ido-completing-read "Select Channel: " nil nil t nil)
  (let ((completion-ignore-case t)) (funcall slack-completing-read-function (format "%s" "Select Channel: ") alist nil t nil))
  (let* ((G54 (let ((completion-ignore-case t)) (funcall slack-completing-read-function (format "%s" "Select Channel: ") alist nil t nil))) (selected (cdr (cl-assoc G54 alist :test (function string=))))) selected)
  (let* ((alist (let (--cl-latest-ts-- --cl-sort-rooms--) (setq --cl-latest-ts-- (function (lambda (room) (let* ((object room)) (if (slot-value object 'latest) (slack-ts (slot-value object 'latest)) "0"))))) (setq --cl-sort-rooms-- (function (lambda (rooms) (nreverse (cl-sort rooms (function string<) :key (function (lambda (name-with-room) (funcall --cl-latest-ts-- (cdr name-with-room))))))))) (funcall --cl-sort-rooms-- (let* ((--cl-var-- (if (function (lambda (rs) (cl-remove-if (function slack-room-hidden-p) rs))) (funcall (function (lambda (rs) (cl-remove-if (function slack-room-hidden-p) rs))) rooms) rooms)) (room nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq room (car --cl-var--)) (setq --cl-var-- (cons (cons (slack-room-label room team) room) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)))))) (let* ((G54 (let ((completion-ignore-case t)) (funcall slack-completing-read-function (format "%s" "Select Channel: ") alist nil t nil))) (selected (cdr (cl-assoc G54 alist :test (function string=))))) selected))
  slack-room-select(nil #<slack-team slack-team>)
  (let* ((team (slack-team-select)) (candidates (let* ((--cl-var-- (list team)) (team nil) (ims nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq team (car --cl-var--)) (setq ims (cl-remove-if (function (lambda (im) (not (eieio-oref im 'is-open)))) (eieio-oref team 'ims))) (setq --cl-var-- (nconc (nreverse ims) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--))) (room (slack-room-select candidates team))) (slack-room-display room team))
  slack-im-select()
  funcall-interactively(slack-im-select)
  #<subr call-interactively>(slack-im-select record nil)
  apply(#<subr call-interactively> slack-im-select (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> slack-im-select record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (slack-im-select record nil))
  call-interactively(slack-im-select record nil)
  command-execute(slack-im-select record)
  helm-M-x(nil #("slack-im-select" 0 15 (match-part "slack-im-select")))
  funcall-interactively(helm-M-x nil #("slack-im-select" 0 15 (match-part "slack-im-select")))
  #<subr call-interactively>(helm-M-x nil nil)
  apply(#<subr call-interactively> helm-M-x (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> helm-M-x nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (helm-M-x nil nil))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

**Comment by ErwinJunge** [comment] 2018-11-13 09:18
Duplicate of #341

**Closed** 2019-12-28 03:40 UTC
